# 공격 탐지 모델 선정 및 공통 컬럼 선택
기본 전처리 → 모델 비교 → CatBoost 중요도 계산 → 중요도 하위 공통 컬럼 삭제 → CatBoost 삭제 전후 F1 비교

In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import display

# 공격별 전처리 함수 불러오기
from process_attacks import (
    DUPLICATE_COLUMNS_TO_DROP,
    find_duplicate_column_pairs,
    load_data,
    preprocess_bruteforce,
    preprocess_dos,
)

# 모델 비교 및 컬럼 중요도 계산 함수 불러오기
from feature_selection_pipeline import (
    build_comparison_table,
    calculate_feature_importance,
    compare_models,
    create_selected_model,
    evaluate_model,
    find_common_low_importance_columns,
    select_best_model,
)

# 표 출력 형식 설정
pd.set_option("display.max_rows", None)
pd.set_option("display.float_format", lambda value: f"{value:.6f}")
pd.set_option("display.max_columns", None)

1. 기본 전처리 데이터 준비

In [2]:
# CSV 파일 경로 설정
BASE_DIR = Path.cwd()
BRUTE_CSV = BASE_DIR / "BruteForce.csv"
DOS_CSV = BASE_DIR / "DoS.csv"

# 공격별 데이터에서 전체 행의 값이 같은 중복 컬럼 확인
brute_raw = load_data(BRUTE_CSV)
dos_raw = load_data(DOS_CSV)
brute_duplicate_pairs = find_duplicate_column_pairs(brute_raw)
dos_duplicate_pairs = find_duplicate_column_pairs(dos_raw)
del brute_raw
del dos_raw

print("Brute Force 중복 컬럼 검사 결과")
display(brute_duplicate_pairs)

print("\nDoS 중복 컬럼 검사 결과")
display(dos_duplicate_pairs)

# 두 공격에서 동일하게 나타난 중복 컬럼 쌍 추출
common_duplicate_pairs = brute_duplicate_pairs.merge(
    dos_duplicate_pairs,
    on=["기준 컬럼", "중복 컬럼"],
    how="inner",
)
print("\n두 공격의 공통 중복 컬럼 검사 결과")
display(common_duplicate_pairs)

# 의미가 다른 TCP 플래그는 제외하고 안전한 중복 컬럼만 삭제
verified_duplicate_columns = set(
    common_duplicate_pairs["중복 컬럼"]
)
unverified_columns = set(DUPLICATE_COLUMNS_TO_DROP) - verified_duplicate_columns

print("\n모델 선정 후 삭제 실험에 사용할 공통 중복 컬럼")
display(pd.DataFrame({
    "삭제 컬럼": DUPLICATE_COLUMNS_TO_DROP
}))

# 공격별 데이터 전처리
X_brute, y_brute = preprocess_bruteforce(BRUTE_CSV)
X_dos, y_dos = preprocess_dos(DOS_CSV)

# 두 데이터에서 공통으로 존재하는 컬럼만 사용
common_features = X_brute.columns.intersection(X_dos.columns).tolist()
X_brute = X_brute[common_features].copy()
X_dos = X_dos[common_features].copy()

# 전처리 결과 확인
print(f"\nBrute Force: {X_brute.shape}, 공격 수: {int(y_brute.sum())}")
print(f"\nDoS: {X_dos.shape}, 공격 수: {int(y_dos.sum())}")
print(f"\n공통 입력 컬럼 수: {len(common_features)}")

Brute Force 중복 컬럼 검사 결과

                         기준 컬럼                 중복 컬럼
0            Total Fwd Packets   Subflow Fwd Packets
1       Total Backward Packets   Subflow Bwd Packets
2  Total Length of Fwd Packets     Subflow Fwd Bytes
3       Fwd Packet Length Mean  Avg Fwd Segment Size
4                Fwd PSH Flags        SYN Flag Count
5            Fwd Header Length   Fwd Header Length.1
6               RST Flag Count        ECE Flag Count

DoS 중복 컬럼 검사 결과

                         기준 컬럼                 중복 컬럼
0            Total Fwd Packets   Subflow Fwd Packets
1       Total Backward Packets   Subflow Bwd Packets
2  Total Length of Fwd Packets     Subflow Fwd Bytes
3       Fwd Packet Length Mean  Avg Fwd Segment Size
4                Fwd PSH Flags        SYN Flag Count
5            Fwd Header Length   Fwd Header Length.1

두 공격의 공통 중복 컬럼 검사 결과

                         기준 컬럼                 중복 컬럼
0            Total Fwd Packets   Subflow Fwd Packets
1       Total Backward Packets   Subflow Bwd Packets
2  Total Length of Fwd Packets     Subflow Fwd Bytes
3       Fwd Packet Length Mean  Avg Fwd Segment Size
4                Fwd PSH Flags        SYN Flag Count
5            Fwd Header Length   Fwd Header Length.1

모델 선정 후 삭제 실험에 사용할 공통 중복 컬럼

                  삭제 컬럼
0   Subflow Fwd Packets
1   Subflow Bwd Packets
2     Subflow Fwd Bytes
3  Avg Fwd Segment Size
4   Fwd Header Length.1

Brute Force: (169558, 68), 공격 수: 1507

DoS: (691395, 68), 공격 수: 251712

공통 입력 컬럼 수: 68

2. 삭제 전 모델 비교 및 모델 선정

In [3]:
# 컬럼 삭제 전 모델별 F1 점수 계산
brute_before = compare_models(
    X_brute,
    y_brute,
    "Brute Force",
    include_svc=True,
)

# DoS의 파일 크기 때문에 SVC 모델 실행 시간이 매우 길어짐 =>  DoS에서만 제외
dos_before = compare_models(
    X_dos,
    y_dos,
    "DoS",
    include_svc=False,
)

# 두 공격의 평균 F1을 계산하여 최적 모델 선정
before_table = build_comparison_table(
    brute_before,
    dos_before,
    "삭제 전",
)
selected_model_name = select_best_model(before_table)

# 모델 선정 결과 출력
print(f"선정 모델: {selected_model_name}")
display(before_table.style.format({
    "Brute Force F1": "{:.6f}",
    "DoS F1": "{:.6f}",
    "Average F1": "{:.6f}",
}))

선정 모델: CatBoost

3. 선정된 CatBoost로 두 데이터의 컬럼 중요도 계산

In [4]:
# 중요도와 삭제 전후 비교에 사용할 CatBoost 생성
importance_model_name = "CatBoost"
selected_model = create_selected_model(importance_model_name)

# 동일한 모델로 공격별 컬럼 중요도 계산
brute_importance = calculate_feature_importance(
    X_brute,
    y_brute,
    selected_model,
)
dos_importance = calculate_feature_importance(
    X_dos,
    y_dos,
    selected_model,
)

# Brute Force 중요도를 내림차순으로 출력
print("Brute Force 컬럼 중요도")
display(brute_importance.sort_values(
    by="Importance", ascending=False
).reset_index(drop=True))

# DoS 중요도를 내림차순으로 출력
print("DoS 컬럼 중요도")
display(dos_importance.sort_values(
    by="Importance", ascending=False
).reset_index(drop=True))

Brute Force 컬럼 중요도

                        Feature  Importance
0              Destination Port   18.357938
1                   Fwd IAT Min    9.810886
2                 Bwd Packets/s    6.395836
3              act_data_pkt_fwd    6.356769
4                  Flow IAT Min    4.848302
5          min_seg_size_forward    3.945851
6                   Fwd IAT Std    3.265994
7         Fwd Packet Length Max    3.135669
8             Fwd Header Length    2.715922
9                  Flow IAT Max    2.595344
10            Subflow Fwd Bytes    2.539567
11                 Flow Bytes/s    2.372269
12                 Fwd IAT Mean    2.242665
13                Fwd Packets/s    2.242397
14          Average Packet Size    1.894517
15            Bwd Header Length    1.879872
16      Init_Win_bytes_backward    1.864207
17            Min Packet Length    1.844427
18       Init_Win_bytes_forward    1.759578
19       Fwd Packet Length Mean    1.622046
20  Total Length of Fwd Packets    1.417092
21                  Bwd IAT Min    1.134664
22                Flow IAT Mean    0.996965
23            Max Packet Length    0.973001
24                  Active Mean    0.970994
25            Packet Length Std    0.878273
26                    Idle Mean    0.847474
27                Fwd IAT Total    0.835931
28          Fwd Header Length.1    0.833563
29                     Idle Max    0.778225
30                  Fwd IAT Max    0.747939
31               URG Flag Count    0.743707
32          Subflow Fwd Packets    0.681951
33                Flow Duration    0.663570
34                 Bwd IAT Mean    0.631036
35         Avg Fwd Segment Size    0.621146
36               Flow Packets/s    0.467362
37       Packet Length Variance    0.447976
38                  Bwd IAT Max    0.385769
39           Packet Length Mean    0.382516
40       Total Backward Packets    0.373609
41            Total Fwd Packets    0.330634
42        Fwd Packet Length Std    0.326305
43  Total Length of Bwd Packets    0.241600
44                   Active Std    0.214535
45                  Bwd IAT Std    0.213820
46            Subflow Bwd Bytes    0.176038
47                Bwd IAT Total    0.160730
48         Avg Bwd Segment Size    0.143131
49        Bwd Packet Length Min    0.140107
50               ACK Flag Count    0.096808
51                Down/Up Ratio    0.081260
52                 Flow IAT Std    0.073177
53        Bwd Packet Length Std    0.072277
54          Subflow Bwd Packets    0.054973
55       Bwd Packet Length Mean    0.050071
56               SYN Flag Count    0.034417
57        Fwd Packet Length Min    0.028294
58        Bwd Packet Length Max    0.021494
59                   Active Max    0.012196
60                   Active Min    0.011658
61                Fwd PSH Flags    0.006609
62                     Idle Std    0.003723
63                     Idle Min    0.003300
64               FIN Flag Count    0.000028
65               RST Flag Count    0.000000
66               ECE Flag Count    0.000000
67               PSH Flag Count    0.000000

DoS 컬럼 중요도

                        Feature  Importance
0              Destination Port   33.797938
1         Bwd Packet Length Std   14.254925
2            Packet Length Mean    5.943288
3       Init_Win_bytes_backward    4.307416
4        Init_Win_bytes_forward    4.259098
5                 Bwd Packets/s    4.174051
6             Min Packet Length    3.138663
7         Bwd Packet Length Min    2.355324
8                  Flow IAT Min    2.304895
9                 Flow Duration    1.776748
10                 Flow Bytes/s    1.659709
11               PSH Flag Count    1.533617
12         Avg Bwd Segment Size    1.514617
13                  Fwd IAT Min    1.338073
14        Fwd Packet Length Min    1.103770
15         min_seg_size_forward    1.094018
16  Total Length of Bwd Packets    0.961666
17                Fwd Packets/s    0.926075
18       Bwd Packet Length Mean    0.890987
19       Total Backward Packets    0.871736
20               FIN Flag Count    0.844387
21          Average Packet Size    0.839047
22            Fwd Header Length    0.769597
23                Down/Up Ratio    0.698516
24            Subflow Bwd Bytes    0.639396
25                    Idle Mean    0.608466
26  Total Length of Fwd Packets    0.604523
27        Fwd Packet Length Max    0.601602
28          Fwd Header Length.1    0.536563
29            Subflow Fwd Bytes    0.432981
30                Flow IAT Mean    0.426670
31            Bwd Header Length    0.366084
32                Fwd IAT Total    0.350309
33                     Idle Min    0.349159
34         Avg Fwd Segment Size    0.321375
35       Packet Length Variance    0.312542
36               URG Flag Count    0.303929
37                     Idle Max    0.287356
38                 Fwd IAT Mean    0.232313
39                 Flow IAT Std    0.227843
40                 Flow IAT Max    0.191828
41        Bwd Packet Length Max    0.174210
42        Fwd Packet Length Std    0.152722
43             act_data_pkt_fwd    0.142470
44            Max Packet Length    0.138416
45               ACK Flag Count    0.128071
46                  Fwd IAT Max    0.124522
47            Packet Length Std    0.100940
48                  Bwd IAT Min    0.100419
49          Subflow Bwd Packets    0.095709
50                   Active Max    0.087468
51                  Bwd IAT Max    0.079233
52                  Fwd IAT Std    0.078775
53               SYN Flag Count    0.075120
54          Subflow Fwd Packets    0.074452
55       Fwd Packet Length Mean    0.064967
56               Flow Packets/s    0.062307
57                     Idle Std    0.061888
58                Bwd IAT Total    0.042155
59                Fwd PSH Flags    0.031322
60                 Bwd IAT Mean    0.030437
61                   Active Min    0.003300
62                  Active Mean    0.000000
63                   Active Std    0.000000
64            Total Fwd Packets    0.000000
65               ECE Flag Count    0.000000
66                  Bwd IAT Std    0.000000
67               RST Flag Count    0.000000

4. 중요도 0.1 이하 공통 컬럼 선정 및 삭제

In [5]:
# 두 공격에서 모두 중요도 0.1 이하인 컬럼 추출
common_drop_columns = find_common_low_importance_columns(
    brute_importance,
    dos_importance,
    threshold=0.1,
)
print(f"삭제 기준: 두 데이터 모두 중요도 <= 0.1")
print(f"공통 삭제 컬럼 수: {len(common_drop_columns)}")
display(pd.DataFrame({"공통 삭제 컬럼": common_drop_columns}))

# 공통 중복 컬럼과 공통 저중요도 컬럼을 하나의 삭제 목록으로 통합
all_drop_columns = sorted(
    set(DUPLICATE_COLUMNS_TO_DROP) | set(common_drop_columns)
)

# ===== 실제 두 데이터셋에 존재하는 컬럼만 남김 =====
all_drop_columns = [
    column
    for column in all_drop_columns
    if column in X_brute.columns and column in X_dos.columns
]

# 모델 선정 후 컬럼 삭제 실험 진행
X_brute_reduced = X_brute.drop(
    columns=all_drop_columns
).copy()

X_dos_reduced = X_dos.drop(
    columns=all_drop_columns
).copy()

y_brute_reduced = y_brute.copy()
y_dos_reduced = y_dos.copy()

# 삭제 후에도 두 데이터의 입력 컬럼 순서를 동일하게 정렬
remaining_features = X_brute_reduced.columns.intersection(
    X_dos_reduced.columns
).tolist()

X_brute_reduced = X_brute_reduced[remaining_features].copy()
X_dos_reduced = X_dos_reduced[remaining_features].copy()

print(f"삭제 후 공통 입력 컬럼 수: {len(remaining_features)}")

삭제 기준: 두 데이터 모두 중요도 <= 0.1
공통 삭제 컬럼 수: 8

              공통 삭제 컬럼
0           Active Max
1           Active Min
2       ECE Flag Count
3        Fwd PSH Flags
4             Idle Std
5       RST Flag Count
6       SYN Flag Count
7  Subflow Bwd Packets

삭제 후 공통 입력 컬럼 수: 56

5. 중복 / 저중요도 컬럼 삭제 후 CatBoost F1 비교

In [6]:
# CatBoost의 삭제 전 F1 가져오기
selected_before = before_table[
    before_table["Model"] == importance_model_name
].iloc[0]

# 중복 / 저중요도 컬럼 삭제 후 CatBoost F1 다시 계산
brute_after_f1 = evaluate_model(
    X_brute_reduced,
    y_brute_reduced,
    selected_model,
)
dos_after_f1 = evaluate_model(
    X_dos_reduced,
    y_dos_reduced,
    selected_model,
)

# 공격별 삭제 전후 F1 비교표 생성
catboost_f1_comparison = pd.DataFrame([
    {
        "Dataset": "Brute Force",
        "Model": importance_model_name,
        "삭제 전 F1": selected_before["Brute Force F1"],
        "삭제 후 F1": brute_after_f1,
    },
    {
        "Dataset": "DoS",
        "Model": importance_model_name,
        "삭제 전 F1": selected_before["DoS F1"],
        "삭제 후 F1": dos_after_f1,
    },
])
catboost_f1_comparison["F1 변화"] = (
    catboost_f1_comparison["삭제 후 F1"]
    - catboost_f1_comparison["삭제 전 F1"]
)

display(catboost_f1_comparison.style.format({
    "삭제 전 F1": "{:.6f}",
    "삭제 후 F1": "{:.6f}",
    "F1 변화": "{:+.6f}",
}))

#### 이미 정제되어있던 연구용.csv을 대상으로 하다보니 오히려 colunm 삭제가 F1 score 하락 원인이 되는 것을 확인 가능하였다.

#### 따라서 중요도가 낮더라도 전처리는 값이 비어있거나, 중복된 값만 colunms 제거를 마친 후 모델 학습 진행 예정이다.